M48
; DRILL file {KiCad 9.0.3} date 2025-09-24T14:37:44+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-24T14:37:44+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0984
%
G90
G05
T1
X6.8159Y-4.4705
T2
X4.3898Y-3.3622
T3
X7.6427Y-4.4705
T4
X4.7146Y-3.878
X6.2756Y-4.4469
X6.3642Y-3.8071
M30
